# Generated by Django 4.2.1 on 2023-06-01 13:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("appSalama", "0002_customuser_groups_customuser_is_superuser_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="cours",
            options={"verbose_name": "Cour"},
        ),
        migrations.RenameField(
            model_name="article",
            old_name="publié",
            new_name="publie",
        ),
        migrations.AlterField(
            model_name="article",
            name="image",
            field=models.ImageField(upload_to="article"),
        ),
        migrations.AlterField(
            model_name="partenaire",
            name="date",
            field=models.DateField(blank=True, verbose_name="Date"),
        ),
        migrations.AlterField(
            model_name="partenaire",
            name="image",
            field=models.ImageField(upload_to="partenaire"),
        ),
    ]
